### ISSUE TITLE
http://www.google.co.jp/search?q=4be80492

### ISSUE THREAD

**Issue by dkhokhlov** [Twitter4J/Twitter4J#330]
Yesterday I started getting this exception in getUserTimeline(). Version 4.0.7. 
Everything was fine before that for quite long time. 
The error reason is unclear.
Any ideas?

==================================================
Java exception occurred:
Connection reset
Relevant discussions can be found on the Internet at:
	http://www.google.co.jp/search?q=4be80492 or
	http://www.google.co.jp/search?q=0c126b1f
TwitterException{exceptionCode=[4be80492-0c126b1f d7e149ce-763af488], statusCode=-1, message=null, code=-1, retryAfter=-1, rateLimitStatus=null, version=4.0.7}

	at twitter4j.HttpClientImpl.handleRequest(HttpClientImpl.java:185)

	at twitter4j.HttpClientBase.request(HttpClientBase.java:57)

	at twitter4j.HttpClientBase.get(HttpClientBase.java:75)

	at twitter4j.TwitterImpl.get(TwitterImpl.java:2084)

	at twitter4j.TwitterImpl.getUserTimeline(TwitterImpl.java:152)

Caused by: java.net.SocketException: Connection reset

**Comment by yusuke** [comment]
Hello,

You may need to upgrade your JDK.

Best regards,
-- 
Yusuke Yamamoto
https://samuraism.com/

**Comment by dkhokhlov** [comment]
I am using java 1.7, hard to change. 
Is it about SSL certs? Is there easy way to upgrade certs or suppress the certs check in this API lib?

Thank you

**Comment by sudutgalau** [comment]
hello yusuke,

i have same problem with dkhokhlov,
i have upgrade my JDK, but I got same error.

==================================================
Java exception occurred:
Connection reset
Relevant discussions can be found on the Internet at:
http://www.google.co.jp/search?q=4be80492 or
http://www.google.co.jp/search?q=0c126b1f
TwitterException{exceptionCode=[4be80492-0c126b1f d7e149ce-763af488], statusCode=-1, message=null, code=-1, retryAfter=-1, rateLimitStatus=null, version=4.0.7}

at twitter4j.HttpClientImpl.handleRequest(HttpClientImpl.java:185)

at twitter4j.HttpClientBase.request(HttpClientBase.java:57)

at twitter4j.HttpClientBase.get(HttpClientBase.java:75)

at twitter4j.TwitterImpl.get(TwitterImpl.java:2084)

at twitter4j.TwitterImpl.getUserTimeline(TwitterImpl.java:152)
Caused by: java.net.SocketException: Connection reset

**Comment by dkhokhlov** [comment]
Upgraded to Java to 8. works now. Must be ssl...

**Comment by itapechang** [comment]
> hello yusuke,
> 
> i have same problem with dkhokhlov, i have upgrade my JDK, but I got same error.
> 
> ================================================== Java exception occurred: Connection reset Relevant discussions can be found on the Internet at: http://www.google.co.jp/search?q=4be80492 or http://www.google.co.jp/search?q=0c126b1f TwitterException{exceptionCode=[4be80492-0c126b1f d7e149ce-763af488], statusCode=-1, message=null, code=-1, retryAfter=-1, rateLimitStatus=null, version=4.0.7}
> 
> at twitter4j.HttpClientImpl.handleRequest(HttpClientImpl.java:185)
> 
> at twitter4j.HttpClientBase.request(HttpClientBase.java:57)
> 
> at twitter4j.HttpClientBase.get(HttpClientBase.java:75)
> 
> at twitter4j.TwitterImpl.get(TwitterImpl.java:2084)
> 
> at twitter4j.TwitterImpl.getUserTimeline(TwitterImpl.java:152) Caused by: java.net.SocketException: Connection reset

I also encountered the same problem, the java version is 8, how did you solve this problem, thanks for sharing
